require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - vendor/**/*
    - bin/**/*

inherit_from: .rubocop_todo.yml
