language: ruby
env:
  global:
    - "JRUBY_OPTS=-Xcext.enabled=true"
rvm:
  - 2.1.2
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - rbx-2.2.10
  - ruby-head
  - jruby-head
  - ree
matrix:
  allow_failures:
    - rvm: ree
    - rvm: ruby-head
    - rvm: jruby-18mode
    - rvm: jruby-head
  fast_finish: true
